### ISSUE TITLE
支持 LuaTeX/upTeX 引擎

### ISSUE THREAD

**Issue by leo-liu** [CasperVector/pkuthss#12]
由于 `pkuthss` 通过 `ctex` 处理汉字问题，可以支持多种引擎。
由于 `pkuthss` 已经依赖 `biblatex`、`caspervector` 这些很新的包，所以可以同时依赖 `ctex` 2。于是可以支持 LuaTeX。TeX Live 2016 (`ctex` 2.4.2) 以后还可以支持 upTeX。

需要做一些修改，避免引擎相关的问题：
- 不要载入 `CJKspace`。新版本的 `ctex` 宏包已经会自动在 pdfTeX 引擎下使用 `CJKspace` 包。其他引擎不需要，目前的判断会出错。
- 不要使用 `\CJKunderline`。如果要避开公式基线的问题，可以改用 `ulem` 包的 `\uline`。
- 其实 Windows/Mac 下不需要重设置字体，Linux 下可以基于 Fandol 重定义一下粗体。LuaTeX 字体设置和 XeTeX 方法相同，若要支持 upTeX 需要手工设置一下。

**Comment by CasperVector** [comment]
pkuthss 里目前计划在 2017 年去掉对 ctex 2.x 以前版本的支持，到时再应用这些变更好了；这个 issue 先留在这里，等搞定之后再 close。
P. S. biblatex （甚至 biblatex-caspervector）出的时间比 ctex 2.x 还是早了不少 = =

**Comment by CasperVector** [comment]
不过有些问题可以提前讨论一下：
* `\CJKunderline` 基本上只用于论文封面的下划线；看 ulem 的说明，似乎它对数学公式的支持有些问题？
* 在 Fandol 支持 GBK 字库之前大概不能采用默认字体设置。

**Comment by leo-liu** [comment]
`CJKfntef` 与 `xeCJKfntef` 都是对 `ulem` 的封装和加强。数学公式兼容性没什么差别了。
话说只用于论文封面下划线，其实调用 `ulem` 都嫌多余。从我内心讲，既然是打印而不是手写，画线根本没意义。

担心 Fandol 缺字的话，直接 `fontset=windowsnew` 好了。

**Comment by CasperVector** [comment]
哦，那样不用 `\CJKunderline` 倒是没啥问题；不过那个下划线还是加好了，免得审论文的人不爽。
字体问题关键是还在 Linux 下的，用 `windowsnew` 还是免不了手动装字体啊。

**Comment by leo-liu** [comment]
用啥不都得手动装字体……
其实 Fandol 可以了，理科其实并没太多 GB2312 以外的需求。

**Comment by CasperVector** [comment]
封面的“二〇一×”……

**Comment by leo-liu** [comment]
「〇」字在新版本的 Fandol Song 中是有的。很早解决了的。
https://github.com/clerkma/fandol-fonts/issues/2

**Comment by CasperVector** [comment]
好吧……

**Comment by CasperVector** [comment]
本 issue 中提到的问题应已修复。
