### ISSUE TITLE
\siunitx中希腊字母输出的问题

### ISSUE THREAD

**Issue by czitian** [CasperVector/pkuthss#13]
问题重现：
\SI{100}{\micro\meter}只会显示 100 M
而$\mu$ 可以正确输出。
环境：
MacTex 2016-06-03 / OSX 10.9
makefile自动编译的，只改了LATEX=xelatex。

thesis.tex:
\documentclass[UTF8]{pkuthss}
\usepackage{siunitx}
\usepackage{amssymb}

\begin{document}
	\SI{100}{\micro\meter}
	$\mu$
\end{document}

不知道是啥问题？

**Comment by CasperVector** [comment]
通过以下代码可重现：
```
PassOptionsToPackage{no-math}{fontspec}
\documentclass[UTF8]{ctexart}
\usepackage{newtxtext, newtxmath, siunitx}

\begin{document}
\SI{100}{\micro\meter} $\upmu$
\end{document}
```
这问题出在底层，呼叫 @leo-liu。

**Comment by leo-liu** [comment]
也不能算是 `ctex` 的问题。如下代码即可重现：
```latex
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{newtxtext,newtxmath}
\usepackage{siunitx}

\begin{document}

\SI{100}{\micro\meter}

$\mu$, $\upmu$, \textmu

\end{document}
```
即使去掉 `newtx` 的两个包也一样，同样可以再现问题。甩锅完毕。


这里可以理解为 `siunitx` 与 `fontspec` 之间的兼容问题。
`\SI` 的第二个参数中的单位是在数学模式下排版的，以此方便支持量纲运算；而按 `siunitx` 的设置，默认情况下单位以 `\mathrm` 排版。
正常情况下，`\mathrm` 的字体就是正文 roman 字体族的字体。`siunitx` 通过检测字体编码，决定 `\micro` 应该用哪个字符（不同编码下字符位置不同）。
如果没有 `no-math` 选项，字体编码是 Unicode 的编码（旧的 EU1 或新的 TU），于是 \mu 是 181 号字符，正常显示。
但如果加了 `no-math` 选项，`fontspec` 会重定义 `\mathrm`，使之使用原来的非 Unicode 编码（OT1 或 T1），此时 `siunitx` 仍然按 Unicode 编码输出 181 号字符，在 OT1 或 T1 编码下的显示就都不对了。
技术分析完毕。


解决此问题，从不同角度都可以。
**`siunitx` 手册已经提及了这个问题**，见 7.6 Symbols and XeTeX 一节。那里给出的方案是 `math-micro = \text{μ}` 这样的设置。注意其他几个符号也可能有此问题。
也可以重定义内部命令 `\SIUnitSymbolMicro`，控制任何你想让它显示的样子，见 `siunitx` 手册 5.15 Symbols 一节。
还有一种办法是避免字体编码的混乱，为此，直接不使用 `newtxtext` 宏包，而是手工设置 Unicode 编码的正文字体。例如字体设置改为：
```latex
\setmainfont{TeX Gyre Termes}
\setsansfont[Scale=MatchUppercase]{TeX Gyre Heros}
\setmonofont[Mapping=]{CMU Typewriter Text}
\RequirePackage{newtxmath}
```
当然，也可以再发信给 `siunitx` 维护者 Joseph Wright，看他能不能检测好 `\mathrm` 等场合的混乱。

**Comment by leo-liu** [comment]
Times 字体族可选的范围也大，除了 TeX Gyre Termes，用 stix 或 XITS 也不错，用操作系统的 Times (New) Roman 也没问题。

**Comment by czitian** [comment]
我测试了@leo-liu 提到的第一种办法方法。（其实第二种也简单试了一下不工作，第三种缺少字体没搞）
根据siunitx manual 2017-01-28 版的 7.6添加了siunitx.cfg文件

但manual里写的那两种都不工作
\sisetup{
  math-micro = \text{μ},
  text-micro  = μ
}
或
\sisetup{
math-micro = \fontspec{Minion Pro} \textmu, 
text-micro = \fontspec{Minion Pro} \textmu
}

我测试了一下CQUthesis发现\SI{}{\micro\meter}正常。
翻了一下发现cquthesis.dtx里有一段

\RequirePackage{siunitx}
\RequirePackage{upgreek}
\ifxetex
\sisetup{%
	math-micro = {\upmu},
	text-micro = {\textmu},
}%\sisetup
\fi

这个放在siunitx.cfg里给pkuthss是工作的。
问题仿佛出在\textmu上。SI里用\textmu就不工作，\upmu就可以正常工作。

anyway，得赶紧写论文了不研究这个了。
谢谢二位！
