### ISSUE TITLE
在win10 下编译模板出错

### ISSUE THREAD

**Issue by nm46nm** [CasperVector/pkuthss#15]
新手一枚
windows10+Miktex+taxmaker，按说明安装了pkuthss，提示安装成功。
用taxmaker打开pkuthss/doc/gbkcrlf/pkuthss.tex，进行快速构建，下载了一堆依赖包之后，提示错误：
```
! FancyVerb Error:
No verbatim file pkuthss-extra.sty
! FancyVerb Error:
Empty verbatim environment
```
请问这是怎么回事？pkuthss-extra.sty这个文件是有的啊，这个pkuthss.tex不能直接构建吗

**Comment by CasperVector** [comment]
https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&type=0&postid=14680715
