### ISSUE TITLE
如何更改参考文献格式为gb/t？

### ISSUE THREAD

**Issue by nm46nm** [CasperVector/pkuthss#17]
新手一枚。
不是很了解tex的原理过程等，在thesis中`\usepackage[backend = biber, style = caspervector, utf8, sorting = ecnty]{biblatex}`应该就是参考文献格式的一些设置吧，怎么把格式改成gb/t呢？是直接把caspervector改成gbt-7714-plain吗？感觉不对啊

**Comment by CasperVector** [comment]
请参考 https://github.com/hushidong/biblatex-gb7714-2015。
