### ISSUE TITLE
中文部分显示乱码

### ISSUE THREAD

**Issue by Pekuuu** [CasperVector/pkuthss#18]
您好，我用texshop打开thesis.txt文件之后（还未进行编译）中文显示是乱码，编码方式选UTF8之后还是乱码。

另外第一遍latex编译报错!pdfTeX error: /Library/TeX/texbin/pdflatex (file simsun.ttc): cannot open True
Type font file for reading，请问怎么解决？非常感谢！

**Comment by CasperVector** [comment]
参考 [《TeX Live + pkuthss 安装使用傻瓜指南》](https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&type=0&postid=14680715)。

**Comment by CasperVector** [comment]
TeX Live 2018 里的话，应该是按 C 所得菜单里的“TeXworks editor; TL includes only the Windows binary”（S 选项）吧。

**Comment by Pekuuu** [comment]
按C之后没有显示这个。。不知道哪里出了问题。可能因为我之前安装过mactex2018，但是卸载原有tex live之后依然是一样的状况，所以现在我又自己把mactex装回去了。
另外我直接试了一下3.3.3，终端里输入texdoc pkuthss之后打开了readme.pdf，这样就可以了吗？请问pdf在预览里面打开了，但怎么知道着个文件所在的文件夹？spotlight里搜不到readme.pdf

**Comment by Pekuuu** [comment]
是这样的
===============================================================================
Options customization:

 <P> use letter size instead of A4 by default: [ ]
 <E> execution of restricted list of programs: [X]
 <F> create all format files:                  [X]
 <D> install font/macro doc tree:              [X]
 <S> install font/macro source tree:           [X]
 <L> create symlinks in standard directories:  [X]
            binaries to: R
            manpages to: –“binaries to”：/usr/local/bin 。
                info to: –“manpages to”：/usr/local/share/man 。

Actions: (disk space required: 5464 MB)
 <R> return to main menu
 <Q> quit

**Comment by CasperVector** [comment]
你要先输入 R（ return to main menu）再按 C……

**Comment by Pekuuu** [comment]
啊不好意思。。。但是I之后依然安装失败
Enter command: I
Installing to: /usr/local/texlive/2018
./install-tl: open(>/usr/local/texlive/2018/tlpkg/texlive.tlpdb.tmp) failed: Permission denied at tlpkg/TeXLive/TLPDB.pm line 628, <STDIN> line 12.

**Comment by Pekuuu** [comment]
还是没弄出来，我决定放弃了，改用Windows吧。

总之很感谢你做的这些工作！

**Comment by CasperVector** [comment]
你安装时用了 root 权限吗 = =？

**Comment by Pekuuu** [comment]
之前以为不需要root权限的。。现在安装好了。运行texdoc pkuthss之后打开了readme，但是这个文件在哪里怎么看呢

**Comment by CasperVector** [comment]
取决于你的 pdf 查看器，可以去网上搜一下……

**Comment by Pekuuu** [comment]
我的天啊终于弄好了！另外，建议可以在教程里加上关于fontset文件里怎么修改字体名称的说明，因为Mac默认的中文字体名可能不是simfang simkai而是FangSong KaiTi之类的。之前各种出问题，核查之后感觉字体文件都是全的但依然报错，后来才发现原来是字体名字不一样。再就是现在pdflatex的编译还是失败，但是xelatex的那个方式成功了。

非常感谢你！准备用latex写论文去了。

**Comment by CasperVector** [comment]
指南里写了 Mac 系统下要用 xelatex 编译的。
