### ISSUE TITLE
Redundant symbols in "ctex-fontset-pkuthss.def"

### ISSUE THREAD

**Issue by Milozms** [CasperVector/pkuthss#20]
In line 39/44/45 there are redundant "[]" symbols, causing compiling errors

**Comment by CasperVector** [comment]
I cannot reproduce the issue on my machine with all TeXLive packages updated to the latest releases.
(Using the example template, with `LATEX` set to any of `latex`, `pdflatex` and `xelatex`).

**Comment by CasperVector** [comment]
For the reference, if this does happen with certain (version) combinations of package dependencies, it would probably be the result of `fontspec` explicitly forbidding settings like `SomeFont=[simkai.ttf]`, which seems to not yet be the case at least on my machine.

**Comment by CasperVector** [comment]
Is the problem still present on your system?
I will close this issue if there is no reply in three days; feel free to reopen it if necessary.
