### ISSUE TITLE
不同子文件之间可以相互引用吗？

### ISSUE THREAD

**Issue by jingli90** [CasperVector/pkuthss#22]
比如想在chap/pkuthss-chap1.tex里面引用chap/pkuthss-chap2.tex里面的某一节或者某一张图可以吗？或者说见第x章这个章节数可以通过label来自动计算吗（两章在不同的文件里面）？怎么实现呢？

**Comment by CasperVector** [comment]
可以，直接 `\label`、`\ref` 即可。主文件中的 `\include` 命令基本上就是展开为相应文件的代码，或者相当于说 TeX 最后处理的就是一个单一的文件。
