### ISSUE TITLE
如何更改本模板的数学字体？

### ISSUE THREAD

**Issue by LittleNewton** [CasperVector/pkuthss#24]
首先感谢Casper对于该模板的辛勤付出~

我的论文是数学论文，里面含有大量的公式，我想把公式字体换成Latin Modern Math，请问有什么方案可以做到这一点？

**Comment by CasperVector** [comment]
```
\documentclass[..., nopkufont]{pkuthss}
\usepackage{lmodern}
```

**Comment by LittleNewton** [comment]
抱歉再次叨扰老兄。

如果要把全文的英文字体都改成Latin Modern Math，请问有什么方法吗？

**Comment by CasperVector** [comment]
正文也用数学字体？不知道……

**Comment by LittleNewton** [comment]
> 正文也用数学字体？不知道……

就是让正文的英文字体都换成Latin Modern Math，这个有方法吗

**Comment by CasperVector** [comment]
不应该是正文字体设为 Latin Modern Roman/Sans/Mono，数学字体设为 Latin Modern Math 吗？
刚才的代码片段已经实现了这个需求了啊。

**Comment by lidq92** [comment]
@CasperVector 您好，打扰了。
按照您建议的设置编译后似乎正文里的英文字体也变了。
如果我只希望改变公式里的字体，有方便的设置吗，谢谢！


> \documentclass[..., nopkufont]{pkuthss}
> \usepackage{lmodern}

**Comment by CasperVector** [comment]
```
\documentclass[..., nopkufont]{pkuthss}
\usepackage{lmodern}
\usepackage[defaultsups]{newtxtext}
```

**Comment by lidq92** [comment]
谢谢

**Comment by zbh2047** [comment]
> ```
> \documentclass[..., nopkufont]{pkuthss}
> \usepackage{lmodern}
> ```

似乎用这个方法后，公式中的小括号都显示不出来了，比如$(x,y)$会显示成x,y。但去掉\usepackage{lmodern}后就能正常显示括号了。有没有什么解决办法呢？
