### ISSUE TITLE
How to delete a blank page at the end of a chapter

### ISSUE THREAD

**Issue by jianing-li** [CasperVector/pkuthss#27]
In this template, even page at the end of a chapter is blank, how to delete it?

**Comment by CasperVector** [comment]
`\documentclass{..., openany}[pkuthss]`

**Comment by jianing-li** [comment]
老师：




  您好！




  我是北京大学博士生，用此LateX模板，在章节末尾的偶数页会出现空白页，评审老师们说让把空白页删掉，学生请教您。




  在模板哪个文件，修改哪几行代码？




  谢谢！

  

  祝好！




家宁

=====================

Jianing Li, Ph.D Candidate

Multimedia Learning Group, National Engineering Laboratory for Video Technology, Peking University

Homepage: https://jianing-li.github.io/

Address: Rm. 2604, Sci. Bldg. 2, Peking University, 5 Yiheyuan Rd., Beijing 100871, China








-----原始邮件-----
发件人:"Casper Ti. Vector" <notifications@github.com>
发送时间:2019-11-17 17:58:57 (星期日)
收件人: CasperVector/pkuthss <pkuthss@noreply.github.com>
抄送: "Jianing Li (李家宁)" <lijianing@pku.edu.cn>, Author <author@noreply.github.com>
主题: Re: [CasperVector/pkuthss] How to delete a blank page at the end of a chapter (#27)



Closed #27.

**Comment by jianing-li** [comment]
老师：

   

   已解决，谢谢！

   

   祝好！




家宁








-----原始邮件-----
发件人:"Jianing Li" <lijianing@pku.edu.cn>
发送时间:2019-11-17 18:12:23 (星期日)
收件人: reply@reply.github.com
抄送: caspervector/pkuthss <pkuthss@noreply.github.com>, author <author@noreply.github.com>
主题: Re: Re: [CasperVector/pkuthss] How to delete a blank page at the end of a chapter (#27)



老师：




  您好！




  我是北京大学博士生，用此LateX模板，在章节末尾的偶数页会出现空白页，评审老师们说让把空白页删掉，学生请教您。




  在模板哪个文件，修改哪几行代码？




  谢谢！

  

  祝好！







家宁

=====================

Jianing Li, Ph.D Candidate

Multimedia Learning Group, National Engineering Laboratory for Video Technology, Peking University

Homepage: https://jianing-li.github.io/

Address: Rm. 2604, Sci. Bldg. 2, Peking University, 5 Yiheyuan Rd., Beijing 100871, China








-----原始邮件-----
发件人:"Casper Ti. Vector" <notifications@github.com>
发送时间:2019-11-17 17:58:57 (星期日)
收件人: CasperVector/pkuthss <pkuthss@noreply.github.com>
抄送: "Jianing Li (李家宁)" <lijianing@pku.edu.cn>, Author <author@noreply.github.com>
主题: Re: [CasperVector/pkuthss] How to delete a blank page at the end of a chapter (#27)



Closed #27.
