### ISSUE TITLE
封面侧缝论文标题乱码

### ISSUE THREAD

**Issue by Thesharing** [CasperVector/pkuthss#29]
编译thesis.tex以后惊喜地发现同时编译了spine.tex生成了封面，但是封面侧缝论文标题出现了乱码，找了一下没找到原因所在……而正文thesis.pdf里是正常的，没有出现乱码。

![image](https://user-images.githubusercontent.com/6576831/73872251-51021880-488a-11ea-8311-fc1ff61bd261.png)

环境：Windows 10 + pkuthss v0.1.6 + TeXLive 2019
文件：采用UTF-8编码保存

谢谢作者 👍

**Comment by CasperVector** [comment]
0.1.6？是 1.6.0 吧？无论如何请确认 `spine.tex` 中载入 `ctexart` 文档类时用了 `UTF8` 选项：
```
\documentclass[UTF8, zihao = -4]{ctexart}
```

**Comment by Thesharing** [comment]
我看BBS上写的是v0.1.6😂 我试了一下，问题解决了~ 十分感谢hhh

不过又遇到另一个问题，中英文混杂的标题会出现排版错误，请问该怎么解决呢？

![image](https://user-images.githubusercontent.com/6576831/73921452-5438eb00-4902-11ea-96ef-5a190e600924.png)

**Comment by CasperVector** [comment]
参考下面的年份和学号，用 `\rotatebox`。

**Comment by Thesharing** [comment]
搞定了 谢谢作者 👍
