### ISSUE TITLE
如何转换为docx？

### ISSUE THREAD

**Issue by Gunlance** [CasperVector/pkuthss#31]
pandoc abc.tex --bibliography=thesis.bib --csl=pkuthss\doc\example\thesis.bib -o file.docx 不行。。

**Comment by CasperVector** [comment]
可以直接写成 word 文档，或者逐页截图 =。=

**Comment by Gunlance** [comment]
首先谢谢作者提供的模板！我还想在更改下题目内容避免语气生硬来着
我导说模板生成的pdf格式不对，要换新的。。
看样子只能自己使用word来写模板了么。。。

**Comment by CasperVector** [comment]
导师觉得具体哪里不对？

**Comment by CasperVector** [comment]
？

**Comment by Gunlance** [comment]
又说没问题了。。。我也懵

**Comment by CasperVector** [comment]
这结果的不可重复性堪比隔壁的论文格式审查人员了……
