### ISSUE TITLE
英文摘要标题字体不对

### ISSUE THREAD

**Issue by Gunlance** [CasperVector/pkuthss#32]
英文题目用 Arial 三号字体，居中书写，单倍行距，段前空 24 磅，段后空 18 磅
编译效果是黑体

**Comment by CasperVector** [comment]
你是要去掉粗体，只用 Arial 吗？

**Comment by Gunlance** [comment]
英文摘要由上到下应包含英文题目、作者姓名、专业名称（用括号括起放姓名之
后）、指导教师姓名、“ABSTRACT”、英文摘要内容和关键词（KEY WORDS）。
英文题目用 Arial 三号字体，居中书写，单倍行距，段前空 24 磅，段后空 18 磅。

这是论文写作指南原话。。。难道本硕的要求不同？

**Comment by CasperVector** [comment]
事实上《研究生学位论文写作指南》从头到尾根本没有提到任何部分的文字加粗与否的问题（黑体是字体族，和是否加粗是两回事），因此模版中加粗与否完全是参考现有习惯（特别是 LaTeX 中的习惯）和研究生院网站上的 Word 模版。而且《研究生学位论文写作指南》从发布至今有 5 年，从未有人说审查论文格式的老师对英文摘要标题和“ABSTRACT”加粗与否提出质疑的。
