### ISSUE TITLE
双语论文的设置

### ISSUE THREAD

**Issue by devon-ge** [CasperVector/pkuthss#33]
请问下面这种要求，模板好改吗？

1）封面（参见附件，用中文标题）；

2）版权声明（中文，从校内综合信息门户下载）；

3）英文题目；

4）英文摘要；

5）英文目录；

6）英文序言；

7）英文正文；

8）参考文献；

9）中文题目；

10）中文摘要；

11）中文目录；

12）中文序言；

13）中文正文；

14）参考文献；

15）致谢；

16）学位论文原创性声明和授权使用说明（中文，导师签字；可从校内综合信息门户下载）；

17）封底

============================
学院给了上面这种很奇葩的要求，目前感觉这种设定有点费力气。不知道作者您有什么建议没？直接改，但好像无法生产两种目录，而且是双语。是否更好的方式是直接做两份PDF，然后用\includepdf{}拼接在一起，中文的只留中间部分，涉及的问题应该是页码调整，预期工作量不大。

**Comment by CasperVector** [comment]
建议直接做两份 pdf，英文的可以参考 `pkuthss-english.patch`。

**Comment by devon-ge** [comment]
英文主要就是标题以及目录问题，已经解决 ，谢谢
