### ISSUE TITLE
英文版，references 页眉

### ISSUE THREAD

**Issue by labro** [CasperVector/pkuthss#34]
由于references页眉的存在，Turnitin这样的查重工具，应该是判断全文最后一个reference单词的位置，位置之后的引用都不会重复，但是在references这个页眉之前的引用都会判断为重复。页眉应该是根据chapter名称做的，如何保证其他章节页眉正确的情况下，单单修改reference的页眉呢？

**Comment by CasperVector** [comment]
请参考 `biblatex.def` 中 `\markboth` 相关的代码和 texdoc biblatex 中关于 `\defbibheading` 的说明。
