### ISSUE TITLE
参考文献的数字的绿框有重叠

### ISSUE THREAD

**Issue by Barak123748596** [CasperVector/pkuthss#38]
![image](https://user-images.githubusercontent.com/28422380/83353016-321c1a80-a382-11ea-9742-b8bda46b61e3.png)
类似这样的框会出现重叠，我现在是用的空格空开，但是这个方法不是很优美。请问有相关处理方法吗？

**Comment by CasperVector** [comment]
`研究 \parencite{ref1, ref2}`

**Comment by Barak123748596** [comment]
这样就成了！谢谢您！
