### ISSUE TITLE
如何删除主页中的“研究方向”？

### ISSUE THREAD

**Issue by Barak123748596** [CasperVector/pkuthss#39]
您好，本科生毕业论文没有“研究方向”。我注释direction后，这块还是存在。请问应该怎么直接删掉这个条目？

**Comment by lidq92** [comment]
@Barak123748596 要修改cls文件。

见 [pkuthss.cls](https://github.com/CasperVector/pkuthss/blob/master/tex/pkuthss.cls) 376-377行。

**Comment by CasperVector** [comment]
非常感谢楼上 :)
