### ISSUE TITLE
如何更改封面底部 年月 的字体？

### ISSUE THREAD

**Issue by Gunlance** [CasperVector/pkuthss#40]
打印后学校审核未通过，封面字体与研究生手册中论文封面模板不符

**Comment by Gunlance** [comment]
我吐了，实在找不到什么不符的地方。。。先问问学校吧

**Comment by Sara-HY** [comment]
同问，请问解决了吗？

**Comment by Gunlance** [comment]
直接使用adobe了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sara"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 下午2:37
收件人:&nbsp;"CasperVector/pkuthss"<pkuthss@noreply.github.com&gt;;
抄送:&nbsp;"761192732"<761192732@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CasperVector/pkuthss] 如何更改封面底部 年月 的字体？ (#40)





 
同问，请问解决了吗？

**Comment by lidq92** [comment]
@Gunlance 应该是在[pkuthss.cls](https://github.com/CasperVector/pkuthss/blob/master/tex/pkuthss.cls) 的384行修改`\zihao{-2}`为`\zihao{3}`就满足[指南](https://grs.pku.edu.cn/docs/2019-05/20190524160158375113.pdf)的要求。

**Comment by CasperVector** [comment]
可以考虑用 `ugly` 选项……

**Comment by Gunlance** [comment]
已经使用了ugly
但是对应字体大小还是26
后来看cls时候，我似乎更改什么，又似乎没有更改，重新编译后字体大小又变成了36，符合要求了
我都忘了我是怎么操作的……很迷



---原始邮件---
发件人: "Casper Ti. Vector"<notifications@github.com&gt;
发送时间: 2020年6月20日(周六) 晚上11:04
收件人: "CasperVector/pkuthss"<pkuthss@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Gunlance"<761192732@qq.com&gt;;
主题: Re: [CasperVector/pkuthss] 如何更改封面底部 年月 的字体？ (#40)




 
可以考虑用 ugly 选项……

**Comment by CasperVector** [comment]
已在 commit 92e6eede 中设定 ugly 模式下封面日期用三号字……

**Comment by summercyy** [comment]
学校审核说我cthesisname与模板不符 … 求问应该怎么调

**Comment by CasperVector** [comment]
```
\fancypagestyle{plain}{
    \fancyhead[CE]{\zihao{5}\normalfont{北京大学博士学位论文}}
}
```
