### ISSUE TITLE
latex3依赖 not found

### ISSUE THREAD

**Issue by devon-ge** [CasperVector/pkuthss#41]
重新编译了一下之前写的毕业论文，文章内容无任何改动，出现如下日志

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.77      \ExplLoaderFileDate{expl3.sty}}
                                         %

! LaTeX Error: File `l3backend-xdvipdfmx.def' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: def)

Enter file name:
! Emergency stop.
<read *>

l.148   { \sys_load_backend:n { } }

No pages of output.

这个是pkuthss的问题还是xdvipdfmx的问题？

**Comment by CasperVector** [comment]
请参考 https://tex.stackexchange.com/questions/499082/_/499130 。

**Comment by devon-ge** [comment]
在TeX Live Manager 里面点击`Regenerate filename database`解决了这个问题。其他的方法均无效
