### ISSUE TITLE
请问有没有大神遇到过页眉显示为chapter 1而不是汉字 第一章 的情况啊

### ISSUE THREAD

**Issue by liu-zhenhua** [CasperVector/pkuthss#43]
RT，是系统设置的问题吗？

**Comment by CasperVector** [comment]
可以暂时用旧版 fancyhdr 绕过：https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&postid=23813000。

**Comment by liu-zhenhua** [comment]
> 可以暂时用旧版 fancyhdr 绕过：[https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&postid=23813000。](https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&postid=23813000%E3%80%82)

感恩，已解决~
