### ISSUE TITLE
封面 “姓名”，“学号”等关键词如何修改

### ISSUE THREAD

**Issue by ShirleyMaxx** [CasperVector/pkuthss#44]
hi，非常感谢您的模板~

请问，封面上的固定的关键词可以修改吗？比如“姓名”改成“作者信息”，“导师”改成“指导教师”这样？在pkuthss.cls里面改吗？（不知道怎么改，参考文档2.4节的“高级设置”里面也没有提及）

谢谢！

**Comment by CasperVector** [comment]
要改 `pkuthss-utf8.def` 和 `pkuthss-gbk.def`。

**Comment by ShirleyMaxx** [comment]
解决了，非常感谢！
