### ISSUE TITLE
编译报错 & 编译超时

### ISSUE THREAD

**Issue by newdaylqt** [CasperVector/pkuthss#45]
使用浏览器刷新页面时，概率发生编译超时，概率编译成功。使用页面内ReCompile时，极大概率在章节内（如chap3.tex）报错“Undefined control sequence.”以及“Missing \begin{document}.”。

**Comment by CasperVector** [comment]
用的 overleaf？那个我没有直接参与开发和测试，无法评论。建议先按未名 BBS 上 MathTools 版置底指南操作。

**Comment by newdaylqt** [comment]
谢谢，我已经在本地配环境搞了😂目前没什么问题
