### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by fjn308** [CasperVector/pkuthss#52]
doc/readme/ChangeLog.txt:
2010-03-29, v1.9.0 -> 2021-03-29, v1.9.0
顺便感谢 CasperVector。

**Comment by CasperVector** [comment]
已修复，谢谢。

**Comment by fjn308** [comment]
抱歉打扰，刚刚注意到 [这里](https://gitea.com/CasperVector/pkuthss/commit/45f067957f92112a27c6b9cca22b9b77b9784a9c) 的修改是 2010 -> 2011 而不是 2021，大概是……手滑……了吧。

**Comment by CasperVector** [comment]
已 force push，抱歉 =。=【捂脸.jpg】
