### ISSUE TITLE
Is there any version for English thesis?

### ISSUE THREAD

**Issue by kenghua-huang** [CasperVector/pkuthss#55]
Hi, I'm a student from Peking University HSBC Business School. I'm currently writing my master thesis. Our school requires both Chinese and English version. So I wonder whether there is an English version of template.

Looking forward to your reply!

**Comment by CasperVector** [comment]
You can use [pkuthss-english.patch](https://github.com/CasperVector/pkuthss/blob/master/doc/readme/pkuthss-english.patch).

**Comment by kenghua-huang** [comment]
Thanks!
