### ISSUE TITLE
怎么样才能每一页脚注重新记号呢?

### ISSUE THREAD

**Issue by ZhangYuef** [CasperVector/pkuthss#62]
用了@iofu728-pkuthss 的毕业论文模板，但脚注是每一章重新记号，试着改`.cls`文件也是不行
```
% \RequirePackage{chngcntr}    
% \counterwithout*{footnote}{page}    
\counterwithin*{footnote}{page}
```

**Comment by ZhangYuef** [comment]
加入如下命令orz
```
% 	  Reset the footnote number every page 
    \RequirePackage[perpage]{footmisc}  
```

**Comment by RayXu14** [comment]
> % 	  Reset the footnote number every page 
>     \RequirePackage[perpage]{footmisc}  
>     \RequirePackage[cleardoublepage = current]{scrextend}

会有一大堆warning，而且甚至同一页还会有重复编号

**Comment by CasperVector** [comment]
去掉 scrextend 那一行就可以，thesis.tex 里提示了正确做法的……
