### ISSUE TITLE
编译过程中LaTeX Error: Unknown option `cleardoublepage = current' for package `scrextend

### ISSUE THREAD

**Issue by XGBoost** [CasperVector/pkuthss#63]
rt，应该怎么解决鸭

**Comment by XGBoost** [comment]
下载的是texlive2022的最新版，按照入门教程一步一步来的

**Comment by XGBoost** [comment]
除了上述问题之外，还出现了两个问题
! Package biblatex Error: Patching \MakeUppercase failed.
! Package biblatex Error: Patching \MakeLowercase failed.
请问应该怎么解决鸭~

**Comment by CasperVector** [comment]
请把 pkuthss.cls 中的
```
\RequirePackage[cleardoublepage = current]{scrextend}
```
替换成
```
\RequirePackage{scrextend}
```
后续会发布新版，从而不再须要自行进行这一更改。
biblatex 的错误我这边用示例代码和 readme 文档都重现不出来 - -

**Comment by XGBoost** [comment]
好的，谢谢，我再试试

**Comment by CasperVector** [comment]
刚 `tlmgr update` 了一下就遇上了 biblatex 那个问题 - -
请应用 https://github.com/plk/biblatex/commit/fb65228b 中对 `biblatex.sty` 的更改……

**Comment by XGBoost** [comment]
@CasperVector 
按照上述方案，biblatex的问题已解决，感谢老哥（姐）！
