### ISSUE TITLE
如何更改Make.bat文件内容，从而加速编译？

### ISSUE THREAD

**Issue by XGBoost** [CasperVector/pkuthss#64]
rt，每次我都是点击Make.bat，不知道是不是自己插图太多了，或者是文件太大（看了一下一共是19M），导致每次编译的过程至少要有两分钟左右，并且长时间停留在这个界面：
![image](https://user-images.githubusercontent.com/23393128/180153644-da795207-8dba-4aa1-aa14-65d821f3be21.png)
寻思着有没有更改Make.bat文件里面的参数，从而使用多线程进行加速编译？
小白不太懂bat里面如何设置，不知道有没有懂的老哥给指条明路，Make.bat文件信息如下

```visual basic
@echo off

@rem Copyright (c) 2008-2009 solvethis
@rem Copyright (c) 2010-2012,2019 Casper Ti. Vector
@rem Public domain.

if "%1"=="" goto doc
if "%1"=="doc" goto doc
if "%1"=="clean" (goto clean) else (goto usage)

:doc
latexmk
goto end

:clean
latexmk -c
goto end

:usage
echo %0 [doc] [clean]
goto end

:end
pause

@rem vim:ts=4:sw=4
```

**Comment by CasperVector** [comment]
抱歉，据我所知 LaTeX 没有并行化的功能。
