### ISSUE TITLE
最新版(v1.9.2)编译出来，使用\parencite命令导致文字与中括号的间距过大

### ISSUE THREAD

**Issue by XGBoost** [CasperVector/pkuthss#65]
rt，我是安装的最新版本的pkuthss（v1.9.2），之前安装完之后，就遇到了一些问题，见[链接](https://github.com/CasperVector/pkuthss/issues/63)。不过按照推荐的[链接](https://github.com/plk/biblatex/commit/fb65228b)已经解决。
今天在编译latex的时候，用了\parencite命令（老板觉得这种引用方式对于我们这个研究方向是最舒服的引用方法），然而发现使用\parencite的时候，编译出来的结果是中括号与前面的中文字体间距较大，我特意从pdf拷贝出来为txt，发现中括号前面还有一个空格。如下图所示
![image](https://user-images.githubusercontent.com/23393128/181721009-7ea126c4-4dc3-47a1-9ecd-4b67bb188797.png)
尝试了设置类以及引用bib的设置，似乎都没有作用。我之前有一个师兄，下载的是比1.9.2更老的版本，就没有这个问题。
想问一下有办法去除这个空格吗？非常感谢

**Comment by CasperVector** [comment]
这些空格应该是用 xelatex 编译时 xeXJK 自动添加的……

**Comment by XGBoost** [comment]
@CasperVector 请问有办法解决去除这个空格吗？灰常感谢！
