### ISSUE TITLE
appendix怎么添加呀

### ISSUE THREAD

**Issue by FengZhiheng** [CasperVector/pkuthss#66]
毕业论文中Latex的appendix怎么添加呀，我看模板里只有这一行
\appendix
但是编译出来的pdf文件里没有appendix呀

**Comment by CasperVector** [comment]
https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&type=0&postid=21333237
请见 example.pdf。

**Comment by FengZhiheng** [comment]
> https://bbs.pku.edu.cn/v2/post-read-single.php?bid=346&type=0&postid=21333237 请见 example.pdf。

谢谢，我尝试摸索了一下，问题解决了。我一直在使用Overleaf上写论文，添加Appendix的流程如下：

1、在`main.text`中的`\appendix`下边添加`\include{chap/appendix}`；

2、在`chap`文件夹下创建`appendix.tex`文件；

3、在`appendix.tex`中写附录的内容即可：

```
\chapter{这是附录A的title}
\section{title}
\subsection{subtitle}
\chapter{这是附录B的title}
\section{title}
\subsection{subtitle}
```

4、效果如下：

![](https://imagewwyt-1312423176.cos.ap-guangzhou.myqcloud.com/img/202211141753771.png)
