### ISSUE TITLE
Mathcal Font too Fancy

### ISSUE THREAD

**Issue by ZJZ1223** [CasperVector/pkuthss#69]
作者您好，目前我在使用贵模板时觉得数学字体Mathcal font 太过花哨了，想改为基础字体，如下图由1->2，想请教一下怎么操作
<img width="524" alt="image" src="https://user-images.githubusercontent.com/71306074/230701939-85a11fed-d052-491b-a774-c2e6478db2a0.png">

**Comment by CasperVector** [comment]
`\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}`

**Comment by ZJZ1223** [comment]
> `\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}`

完美解决，感谢

**Comment by CastleStar14654** [comment]
@CasperVector XeLaTeX 用了 `unicode-math`，而 `\mathcal` 和 `\mathscr` 是同一个 Unicode 码位。根据 `unicode-math` 文档的 5.4.3，pkuthss 已经使用的 XITS 字体是目前唯一支持区别 cal 和 scr 的字体。根据[这篇帖子](https://tex.stackexchange.com/questions/184686/how-to-make-calligraphic-numbers-available-with-unicode-math)，只要再加上
```latex
\setmathfont[
	Extension = .otf,
	BoldFont = XITSMath-Bold,
	range={\mathcal,\mathbfcal},
	StylisticSet=1
]{XITSMath-Regular}
```
即可。
