### ISSUE TITLE
章节标题到页眉线的距离如何设置

### ISSUE THREAD

**Issue by dongfengweixiao** [CasperVector/pkuthss#7]
我看了下代码，\CTEXsetup中对chapter的定义，即便是beforeskip设置为0，依旧距离页眉线有很远的距离，尝试对页面设置进行更改，依旧不能奏效，所以想要问下，这个在哪里有额外的设置？

**Comment by CasperVector** [comment]
chapter 到页眉的间距设置的确是比较麻烦，我当时的设定值是手工试出来的。
刚才又试了一下，`beforeskip = {0bp}` 的效果和学校的学位论文写作指南里刚好相近，就用这个值吧。
（之前设定的值是 20bp，不知当时是怎么想的；最新的 commit 里会改。）

**Comment by dongfengweixiao** [comment]
在此情况下，可以发现中文章节还是距离页眉线非常远，而英文的摘要距离页眉线又是另一个距离。。。。

**Comment by CasperVector** [comment]
我这里似乎还好，cf7ff53c 编译出来是附图这样的。
![cf7ff53c-05et07](https://cloud.githubusercontent.com/assets/1498481/7761899/948d37a2-005e-11e5-9951-fec3fe6c35d6.png)

**Comment by dongfengweixiao** [comment]
你可以尝试将abstract上面的部分都去掉，应该就能够看到现象了。应该还是哪里的代码有问题，但是我并没有找到。

2015-05-22 8:43 GMT+08:00 Casper Ti. Vector <notifications@github.com>:

**Comment by CasperVector** [comment]
英文摘要部分的 chapter mark 是英文标题（这里是“PKU dissertation document class ...”），下面用一个 tabular 环境排版英文作者、专业、导师和“ABSTRACT”。“ABSTRACT”不是 chapter mark，自然不太可能和 chapter mark 有类似的格式。

**Comment by dongfengweixiao** [comment]
哦，那就难怪了。。。再看了下代码，cn的是使用的chapter*，而en的并不是。

2015-05-22 9:11 GMT+08:00 Casper Ti. Vector <notifications@github.com>:

**Comment by CasperVector** [comment]
不，`eabstract` 环境的定义里有一行 `\chapter*{\sffamily\@etitle}` 的。
