### ISSUE TITLE
Mac 字体问题

### ISSUE THREAD

**Issue by zhiquanxu** [CasperVector/pkuthss#74]
Mac OS 无法设置英文字体， Times new roman, Arial 等mac私有或开放系统字体均无法显示无法找，而相应字体在字体册和/Library/Fonts/均能找到。设备：Macbook Air m2 , Mac OS 13.0(Ventura)

**Comment by CasperVector** [comment]
按未名 BBS 上 MathTools 版置底（顶）的指南改过 texcnf.cnf 了吗？
