### ISSUE TITLE
\linespread 奇怪的行为

### ISSUE THREAD

**Issue by Firestar-Reimu** [CasperVector/pkuthss#78]
![Screenshot_20230602_225058](https://github.com/CasperVector/pkuthss/assets/65082432/be3afb8b-b0c6-45c9-bb64-06e66254924c)

我的大括号明明括了3段，为什么最后一段没有改行距

**Comment by CasperVector** [comment]
应该是最后一段没有被当成完整段落，后面加个空行或者 `\par` 就行了。
以及那一对大括号不是必需，因为已经在 `eabstract` 环境里面了。
