### ISSUE TITLE
英文文字和公式字体

### ISSUE THREAD

**Issue by lomyal** [CasperVector/pkuthss#8]
首先感谢Casper对于该模板的辛勤付出~

与现在能在bbs上搜到的1.3版本相比，1.6版本中加入了『newtxtext』和『newtxmath』宏包，注释中提到的原因是『提供近似于学校所要求的 Times New Roman / Arial 的字体』。因为使用类似Times New Roman的字体来写英文和公式真的很难看，所以实在不想使用这个字体 :(

我想请问作者，这个改动的初衷是否仅仅是给模板用户提供一个可选的功能？北大教务现在是否会拒收使用TeX默认英文和公式字体的论文（或者说作者是否收到一些同学的反馈，指出教务拒收了没有使用规定英文字体的论文）？

**Comment by CasperVector** [comment]
引入 newtx 系列宏包是为了满足《研究生学位论文写作指南》的要求，有关设定从技术上来说其实都是可选的。至于这些设定是否在行政手续的意义上可选，这个我显然无权决定，但可以确定的是到目前为止，我尚未收到同学因在《研究生学位论文写作指南》发布之后仍然故意不使用 Times New Roman / Arial 而被要求修改论文的报告。

**Comment by lomyal** [comment]
感谢Casper严谨的回答。
我找到了《研究生学位论文写作指南》正在仔细研读，在此给出下载地址供其他同学参考：
http://grs.pku.edu.cn/document/20150304174841917181.pdf
