### ISSUE TITLE
参考文献格式不对？

### ISSUE THREAD

**Issue by Yujie-Cui** [CasperVector/pkuthss#80]
![image](https://github.com/CasperVector/pkuthss/assets/89470132/ad4247ac-907f-43bb-8dd9-938a14273ce6)
您好！ 我在使用这个模板撰写毕业论文之后， 我发现参考文献的格式如上图所示。
首先，作者名字全部大写了， 并且论文名字之后会多两条//。 我观察往年的比特论文，好像并不是这种合适， 请问如何来改正呢？

**Comment by note286** [comment]
可以看一下 GB/T 7714-2015 的示例。

**Comment by CasperVector** [comment]
如楼上所述，你用的文献样式不是 biblatex-caspervector，而是 biblatex-gb7714-2015。

**Comment by Yujie-Cui** [comment]
非常感谢， 我注意到了7714-2015是这个样式。 我希望能和往年毕业论文保持一致。
原来的代码是\usepackage[backend=biber,style=gb7714-2015]{biblatex} 
  % 参考文献遵循GB/T 7714-2015标准，使用biblatex-gb7714-2015 宏包。

当我修改成\usepackage[backend=biber,style=caspervector]{biblatex}， 此时的参考文献的作者名字符合预期了。但是出现了很多其他的问题。
(1).  如下图所示， 出现了乱码， 原来的参考文献的标题以及页眉都出现了问题。
(2).  所有的日期都被加粗了。

![image](https://github.com/CasperVector/pkuthss/assets/89470132/19e695db-0308-46cb-9c12-3cefeac66844)

**Comment by CasperVector** [comment]
乱码问题可以通过在宏包参数中加 `utf8` 解决，年份加粗可以在导言区加 `\toggletrue{bbx:bfdate}` 解决。
如果格式审查中对斜体、引号等附加样式提出意见，可以在宏包参数中加 `ugly` - -

**Comment by Yujie-Cui** [comment]
非常感谢。
1. 但是我发下main.tex中有这句话\usepackage[utf8]{inputenc}。
并且我尝试了在这里添加\usepackage[backend=biber,style=caspervector]{biblatex}[utf8]， 仍然存在乱码。
2. 在导言区加 \toggletrue{bbx:bfdate} 之后， 似乎仍然是黑体。
3.  并且参考文献的列表的序号全部为[0]

![image](https://github.com/CasperVector/pkuthss/assets/89470132/0a4dbff3-b086-4fc8-a909-a4959489ddad)

**Comment by CasperVector** [comment]
应该是 `\usepackage[backend=biber,style=caspervector,utf8]{biblatex}` 和 `\togglefalse{bbx:bfdate}`，后一个之前写反了，抱歉。序号为 0 的问题可以参考 texdoc pkuthss 第 3.2 节中关于 biber 的说明，删除 `par-...` 临时目录，如果还不行建议先在虚拟机里编译 - -

**Comment by Yujie-Cui** [comment]
非常感谢！ 
1. 乱码的问题现在解决了。 
2. 之前我有\togglefalse{bbx:bfdate} 和 \toggletrue{bbx:bfdate}  但是都没有起到作用。 这条语句是写在哪个位置都可以吗？ 我写在了导言区， 紧挨着\usepackage[backend=biber,style=caspervector,utf8]{biblatex}
我重新验证了下， 仍然没有反应。
3. 我使用的是texStudio， 集中工具。 这个怎么删除临时目录呢？ 我在tex文件所在的目录没有找到命名存在par的目录。

**Comment by CasperVector** [comment]
我自己确认了一下，`bbx:bfdate` 那个做法的确已经不能用了，抱歉。
可以去掉 `\togglefalse{bbx:bfdate}`，改为在导言区加入 `\DeclareFieldFormat*{date}{#1}`。

**Comment by Yujie-Cui** [comment]
非常感谢，我发现加上这句话之后，参考文献的黑体消失了。
但现在发现了一个新的问题，那就是正文中的引用也变了。yuan原来引用的位置是[31]， 现在只剩下数字了。
![image](https://github.com/CasperVector/pkuthss/assets/89470132/fac05a81-2832-4b3a-b3e7-19e97a5fa6ef)

**Comment by CasperVector** [comment]
biblatex-caspervector 分了 `\cite`、`\parencite` 和 `\supercite` 这么几种用法，你得自己用对的 - -

**Comment by Yujie-Cui** [comment]
非常感谢， 目前问题全部解决了。
