### ISSUE TITLE
tex包依赖

### ISSUE THREAD

**Issue by ZiyaoLi** [CasperVector/pkuthss#81]
Hi Casper，非常感谢你的模板，不知道你是否还在维护这个项目。

我最近在windows + tex live 安装 pkuthss package （用tlmgr），发现不能自动识别依赖的包（如ctex）并安装，想问问是否有计划解决？谢谢！

**Comment by CasperVector** [comment]
按《TeX Live + pkuthss 安装使用傻瓜指南》配置过了吗？

**Comment by ZiyaoLi** [comment]
安装完整的tex当然不会存在依赖问题，只不过大小会太大，即使在最快的镜像安装也会进行数个小时。

我安装了tex live的medium version，在此基础上应该只需额外安装ctex bibtex等在内的几个包就可以运行了。如果合理配置依赖应该就可以hhh

**Comment by CasperVector** [comment]
哦那可能是 ctex 本身就不在你用的较小版本 texlive 里吧，tlmgr 的确是不自动处理依赖的，我上传包时从没声明过依赖 - -
