### ISSUE TITLE
参考文献中的网址怎么显示？

### ISSUE THREAD

**Issue by Yujie-Cui** [CasperVector/pkuthss#82]
@misc{3ndDataPrefetching2019,
  title = {The 3nd Data Prefetching Championship},
  year = {2019},
  howpublished = {https://dpc3.compas.cs.stonybrook.edu/}
}

您好！ 
我的bib文件里面有上面的条目， 我在正文中引用了上面的条目， 但是不显示具体的网址， 
生成的参考文献是
[1] The 3nd Data Prefetching Championship. 2019.

请问怎么把网址显示出来？

\usepackage[backend=biber,style=caspervector, url=true, utf8]{biblatex}
1. 我在这里添加了url=true， 但没有作用。
2. 我将@misc改成@online， 仍然没有作用。

其次， 我发现很多参考文献的末尾有 accessed on 2023-06-01.， 请问怎么把这个去掉？

**Comment by CasperVector** [comment]
`howpublished` 字段改名为 `url` 就能显示网址了，去掉 `urldate` 字段就能去掉那个时间戳。

**Comment by Yujie-Cui** [comment]
感谢你的回答， 我尝试了下能够解决问题。
1. 我正在使用zotero管理文献， 设置了生成的bib文件一直更新， 请问你知道怎么在导出的时候， 就自动的将 howpublished  改成url。 或者能够自动识别url吗？

**Comment by CasperVector** [comment]
如果用 Linux 的话，执行 `sed -ri 's/^( *)howpublished( *)=/\1url =/' /path/to/file.bib` 应该是一个可行的方案……
