### ISSUE TITLE
急！双盲封面更新

### ISSUE THREAD

**Issue by Panlichen** [CasperVector/pkuthss#83]
刚刚，学校教务发通知，双盲封面改了，加了“学术学位”和"专业学位"的选项。
[更新-【“双盲制”学生看】博士学位论文匿名评阅论文封面（2024）.docx](https://github.com/CasperVector/pkuthss/files/14433201/-.2024.docx)

**Comment by Panlichen** [comment]
正式论文的封面也改了。
[附件1【博士】：博士学位论文封面（2024）.docx](https://github.com/CasperVector/pkuthss/files/14434460/1.2024.docx)

**Comment by CasperVector** [comment]
见刚刚的 [commit](https://github.com/CasperVector/pkuthss/commit/321562bf)。
不过这些新要求是通过微信之类的渠道通知的吗？在研究生院网站上没看见 - -

**Comment by Panlichen** [comment]
感谢！
是今天教务邮件通知的。

这个改动之后会在texlive的新版本中merge吗？

**Comment by CasperVector** [comment]
等正式的通知或者文件出现在学校网站上，之后应该会发布新版本……

**Comment by Panlichen** [comment]
ok~

**Comment by Yujie-Cui** [comment]
> 等正式的通知或者文件出现在学校网站上，之后应该会发布新版本……

您好！ 官网已经更新了。 https://grs.pku.edu.cn/xwgz11/xwsy11/bsxw111/gztz09/index.htm   
[关于完善研究生学位论文封面的通知](https://grs.pku.edu.cn/xwgz11/xwsy11/bsxw111/gztz09/376720.htm)

**Comment by CasperVector** [comment]
已发布新版本并上传到 CTAN……

**Comment by ZiyaoLi** [comment]
求1.9.4的tex包发布，thx!
