### ISSUE TITLE
这两个模板内容一致吗?

### ISSUE THREAD

**Issue by Yujie-Cui** [CasperVector/pkuthss#84]
您好！ 我一直使用的是这个网站的模板。
https://www.overleaf.com/latex/templates/2022-peking-university-master-thesis-template-iofu728-pkuthss/rwfvbkpzydpf

但是今天我发现这个模板和当前的仓库里面的结构并不一致， 它的目录结构是
![image](https://github.com/CasperVector/pkuthss/assets/89470132/b30809b0-afef-49a6-948a-a40dcc5cb5b3)
1. 请问这两个模板内容是一致的吗？
2. 请问LaTex模板满足这些间隔要求吗？我发现学校给的 《[北京大学研究生学位论文写作指南](https://grs.pku.edu.cn/xwgz11/xwsy11/bsxw111/clxz09/346374.htm)》 里面给了很多的行距， 字体设置。 

![image](https://github.com/CasperVector/pkuthss/assets/89470132/bdacd168-1d12-422c-a2de-37912d16273d)

**Comment by CasperVector** [comment]
1. 我不直接维护 overleaf 版的 pkuthss，所以不清楚。
2. 基本是满足的，但学校自己查得也不是非常严（比如最新发布的封面中字号设定就和指南里的有出入），而且指南里的部分设定也挺难看（所以 pkuthss 和 biblatex-caspervector 都有隐藏的 `ugly` 选项）。

**Comment by Yujie-Cui** [comment]
好的 感谢！！！
