### ISSUE TITLE
Package keyval Error: degreetype undefined. }

### ISSUE THREAD

**Issue by Yujie-Cui** [CasperVector/pkuthss#85]
您好， 我刚clone了最新的版本， 但是出现了下面的问题， 似乎是因为degreetype 修改最修改封面的命令出错了。

![image](https://github.com/CasperVector/pkuthss/assets/89470132/785c15ab-d041-4f8a-8103-df821a22bbe0)

注释掉该行 `degreetype = {1},`  便可成功编译。

**Comment by CasperVector** [comment]
如果是自行从 github 下载的最新版，那么你还须要用其中的 `pkuthss-utf8.def`、`pkuthss-gbk.def`、`pkuthss.cls` 替换掉系统中旧版的同名文件。
