### ISSUE TITLE
v1.9.4: 新选项 `degreetype` 未初始化，导致报错 `Undefined control sequence \@degreetype`

### ISSUE THREAD

**Issue by muzimuzhi** [CasperVector/pkuthss#87]
`pkuthss` v1.9.4 (https://github.com/CasperVector/pkuthss/compare/v1.9.3...v1.9.4) 新增了选项 `degreetype`，控制在封面页展示的学位类型。这个选项没有初始化，于是直接运行使用 `pkuthss` 的既有文档会报错
```
! Undefined control sequence.
\HyOrg@maketitle ...}} \vfill \ifnum \@degreetype 
                                                  =1{\zihao {3}\fangsong $\b...
l.45 
```
我遇到的既有文档是 `CTeX-org/ctex-kit` 里的测试文件 [`pkuthss.lvt`](https://github.com/CTeX-org/ctex-kit/blob/37f7b8bcf0e612d4bd1ea7c5d4773db8f5703609/ctex/test/testfiles-contrib/pkuthss.lvt)，这导致 `ctex-kit` 的每周例行[测试失败](https://github.com/CTeX-org/ctex-kit/actions/runs/8203081595/job/22435187182)。

- 如果在设计上是可接受的，建议初始化 `degreetype`。
- 如果是不可接受的，也许封面相关的代码应该检查 `\@degreetype` 是否定义，如果没有定义则提供有意义的报错信息。同时在文档里提及「必须设置 `degreetype`」。

**Comment by muzimuzhi** [comment]
相关实现和文档，从 https://github.com/CasperVector/pkuthss/compare/v1.9.3...v1.9.4 可以一次看全。
https://github.com/CasperVector/pkuthss/blob/29b590a1a59a3b534bb8e7933150f788b76da71a/tex/pkuthss.cls#L257
https://github.com/CasperVector/pkuthss/blob/29b590a1a59a3b534bb8e7933150f788b76da71a/tex/pkuthss.cls#L417-L424
https://github.com/CasperVector/pkuthss/blob/29b590a1a59a3b534bb8e7933150f788b76da71a/tex/pkuthss.cls#L446-L450
https://github.com/CasperVector/pkuthss/blob/29b590a1a59a3b534bb8e7933150f788b76da71a/doc/readme/chap/pkuthss-chap2.tex#L180-L181

**Comment by muzimuzhi** [comment]
根据参考文献《关于完善研究生学位论文封面的通知》，只有研究生学位论文封面需要展示学位类型，也许 `degreetype` 应该初始化为 0。
https://github.com/CasperVector/pkuthss/blob/29b590a1a59a3b534bb8e7933150f788b76da71a/doc/readme/pkuthss.bib#L288-L296
> 为了便于评阅专家更直观地了解论文类型，本学期起，对硕士、博士学位论文封面以及博士学位论文匿名评阅论文封面进行完善。封面增加“学位类型”字段，以区分学术学位论文和专业学位论文，学生可根据实际情况勾选。

目前 `pkuthss` 的文档正是这么设置的。
https://github.com/CasperVector/pkuthss/blob/29b590a1a59a3b534bb8e7933150f788b76da71a/doc/readme/pkuthss.tex#L71

**Comment by CasperVector** [comment]
1. `thesis.tex` 中默认 `degreetype = {0}` 可能让不仔细看的同学忽略这一功能，我个人觉得默认 `degreetype = {1}` 利（稍）大于弊。
2. `degreetype` 和 `ctitle`、`emajor` 等等一些配置项都没有严格意义上的默认值，它们都是在 `thesis.tex` 或 `pkuthss.lvt` 等文件中首次设定的。
3. 因此个人觉得还是在 `pkuthss.lvt` 中设置一个 `degreetype` 更为合适，当然为了处理对旧版 pkuthss 的兼容性问题可能有必要辅以一定的版本判断。

**Comment by muzimuzhi** [comment]
> 2\. `degreetype` 和 `ctitle`、`emajor` 等等一些配置项都没有严格意义上的默认值，它们都是在 `thesis.tex` 或 `pkuthss.lvt` 等文件中首次设定的。

也许 `pkuthss` 文档中需要列举「必须设置的文档信息」。

> 3\. 因此个人觉得还是在 `pkuthss.lvt` 中设置一个 `degreetype` 更为合适，当然为了处理对旧版 pkuthss 的兼容性问题可能有必要辅以一定的版本判断。

我给 `CTeX-org/ctex-kit` 里的 `pkuthss.lvt` 加上了设置 `degreetype={1}`。

**Comment by CasperVector** [comment]
> 也许 `pkuthss` 文档中需要列举「必须设置的文档信息」。
考虑到多数用户的学习和使用习惯，现在推荐的使用方式已经是《TeX Live + pkuthss 安装使用傻瓜指南》了，当然现在也有不少用户用（并不直接由我维护的）overleaf 模版。两者都是基于 `thesis.tex`的，所以也懒得改正式文档了 - -
