### ISSUE TITLE
\paragraph 之间间距有些大

### ISSUE THREAD

**Issue by wtyuan96** [CasperVector/pkuthss#88]
你好，`\paragraph` 之间的间距较 `\section`、`\subsection` 和 `\subsubsection` 都要大，是特意这样的吗？可以自由调整吗？还是说不鼓励用 `\paragraph`？我看好像也不鼓励用 `\subsubsection`。

谢谢。

**Comment by wtyuan96** [comment]
好的，感谢这么及时的回复，已经手动调整。
顺便请教一下，英文摘要里使用 `Chapter~\ref{chap:xxx}` 编译后是中文的数字，譬如 `Chapter 四` ，这个有什么解决方案吗？或者说英文摘要里就不要用 `\ref` 了，手动敲一下章节序号？

**Comment by CasperVector** [comment]
纯西文论文可以打 `doc/readme/pkuthss-english.patch` 这个补丁……

**Comment by wtyuan96** [comment]
好嘞，感谢。
