### ISSUE TITLE
XeTeX 下数学字体设置有误

### ISSUE THREAD

**Issue by leo-liu** [CasperVector/pkuthss#9]
目前版本在示例主文件中使用 `newtxtext` 和 `newtxmath` 宏包来设置英文和数学字体。
但 `newtx` 包并没有对 `XeTeX` 引擎做完整的设置，在使用 XeLaTeX 时，`\mathbf` 等字体会因默认字体编码为 `EU1` 而失效。

示例：
```latex
\documentclass[UTF8]{pkuthss}[2015/06/30]
\usepackage{newtxtext,newtxmath}

\begin{document}

Times $Math$

$\mathbf{Bold?}$

\end{document}

LaTeX Font Warning: Font shape `EU1/ntxtlf/m/n' undefined
(Font)              using `EU1/lmr/m/n' instead on input line 6.

LaTeX Font Warning: Font shape `EU1/ntxtlf/bx/n' undefined
(Font)              using `EU1/ntxtlf/m/n' instead on input line 8.
```

可能的解决方案如：

1. 使用 `\PassOptionsToPackage{no-math}{fontspec}`，或全局 `no-math` 选项。
2. 在 XeTeX 引擎下改用 `TeX Gyre Termes` 或 `XITS` 这些 OpenType 字体作为正文字体。但注意 Linux 环境下用户一般不会安装 `texlive-fontconfig.conf`（见 TeX Live 文档），需要用字体文件名才能找到相应字体。

另外，如果是教务格式要求用 Times/Arial 字体，那么这部分字体设置是不应该放在示例主文件中作为可选项的。没有经验的用户也很不容易设置对。

**Comment by leo-liu** [comment]
另外，`latexsym` 宏包是多余的（`newtx` 会提供）。

**Comment by CasperVector** [comment]
之前更改字体只是加入一行 `\usepackage{newtxtext, newtxmath}` 就完了，后来尽管发现 newtxmath 需要 `defaultsups` 选项但也就多了一行代码而已，因此出于灵活性的考虑没有移进宏包文件里。现在因为有关设定变得复杂了，看来也只能移过去了。

采用 latexsym 是考虑到用户在未使用 newtx 时仍需要产生“□”，且它似乎不怎么和其它宏包冲突。
不过话说回来，latexsym 提供的是 `\Box` 而非 `\square`，之前从 amssymb 迁移到 latexsym 之后很快就又从 Computer Modern / Latin Modern 迁移到了 newtx，因此没有发现这个问题。

**Comment by CasperVector** [comment]
问题已修复。
