### ISSUE TITLE
无法更换学校的原创声明页和版权声明

### ISSUE THREAD

**Issue by Yujie-Cui** [CasperVector/pkuthss#90]
您好， 我使用的事overleaf的版本。  https://www.overleaf.com/latex/templates/2022-peking-university-master-thesis-template-iofu728-pkuthss/rwfvbkpzydpf

里面的版权声明和原创声明是直接插入了pdf。
```
% 此处不用 \specialchap，因为学校要求目录不包括其自己及其之前的内容。
\chapter*{版权声明}
% 综合学校的书面要求及 Word 模版来看，版权声明页不用加页眉、页脚。
\thispagestyle{empty}

任何收存和保管本论文各种版本的单位和个人，
未经本论文作者同意，不得将本论文转借他人，
亦不得随意复制、抄录、拍照或以任何方式传播。
否则一旦引起有碍作者著作权之问题，将可能承担法律责任。

% 替换门户下载pdf
\begin{textblock}{1}(-0.8,-0.08)
    \colorbox{white}{
        \includegraphics[height = 1.2448\textheight]{img/bqsm_190.pdf}
    }
\end{textblock}

% vim:ts=4:sw=4
```

我碰到了一个奇怪的现象， 我从学校官网下载了原创声明和版权声明，并把他们放到了和之前一样的目录。但是编译的时候出现了

![image](https://github.com/CasperVector/pkuthss/assets/89470132/8202758b-d335-44d6-9b5c-f0aa816c944d)

我反复验证文件位于正确的文件内。 但是很奇怪的是一直出现上面的问题。 我选择其他我自己生成的pdf文件，全部编译通过，但是只要换成从学校下载的文件，便出现上面的问题。

**Comment by meta-tabchen** [comment]
我也碰到了和你类似的问题，尝试多次后，找到一种方法。
1、把原模版的pdf下载下来
2、然后编辑 pdf，用学校下载的替换二维码内容，保存
3、然后上传

**Comment by CasperVector** [comment]
可能是官方的声明文件不符合 graphicx 包对格式的要求，要不用 `pdftopdf` 之类的工具转一下试试？
