### ISSUE TITLE
新版博士论文封面编译报错

### ISSUE THREAD

**Issue by yexp11235** [CasperVector/pkuthss#91]
您好, 近期学校更新了博士论文封面, 然后我下载了您的最新版的tex文件, 但是编译出现报错, 报错如下:
![image](https://github.com/CasperVector/pkuthss/assets/51668502/2f180709-bde4-4b5a-bd30-9bd53acc7574)
但我并没有修改'degreetype={1}', 而且不做任何修改, 直接编译doc/example和doc/readme都出现同样报错
我用的是windows编译, 但尝试了换到ubuntu编译也报错
尝试修改latexmkrc中的pdf_mode也不起作用
如果把thesis.tex中的degreetype={1}注释掉, 则不报错, 但又回到了旧版本
能请您看看原因在何处吗? 谢谢

**Comment by yexp11235** [comment]
帮室友调论文格式, 然后找到原因了, 更新到最新的texlive2024就行

**Comment by yexp11235** [comment]
我好像问了一个很蠢的问题哈哈, 本质上是我没把新的package给替换上..., 特别是pkuthss.cls的文件要替换掉, 希望我的愚蠢对大家有帮助哈

**Comment by elenacliu** [comment]
@yexp11235 想请问一下，“我没把新的package给替换上”是什么意思呢？我克隆了最新的仓库，直接执行make，按理来说package什么的应该已经是最新的了？目前我和您遇到了同样的报错。

**Comment by elenacliu** [comment]
我似乎明白了，看了看报错的文件路径，应该是指/usr/local/texlive/2023/texmf-dist/tex/latex/pkuthss这个路径下的def/cls等文件没有更新。
指路：https://github.com/CasperVector/pkuthss/issues/85#issuecomment-1983570728
