### ISSUE TITLE
如何将参考文献更改为APA格式？

### ISSUE THREAD

**Issue by Zorauna** [CasperVector/pkuthss#92]
您好，感谢分享～

我目前使用的是“2022 Peking University Master Thesis Template(iofu728-pkuthss)”版本，希望用现有模板尽快调整为APA格式的参考文献，抱歉自己尝试了很多次都没有成功，总是和包冲突或者缺少定义。求指点！！！

马上就要提交盲审了，真的快要急哭了！！

跪谢！！！

**Comment by Zorauna** [comment]
您好，目前我查到的内容，但是放入文档库中就会出错。谢谢～～
\documentclass{article}
% 加载 apacite 包
\usepackage{apacite} 
% 此处不要加载 natbib 或 biblatex，——已经听话地注释掉，但是依然不行。

\begin{document}

% 文档的内容
...

% 参考文献部分
\bibliographystyle{apacite}
\bibliography{myreferences} % 假设你的 bibtex 文件名为 myreferences.bib

\end{document}

**Comment by leavelet** [comment]
您好：
将引入`biblatex`的一行改为如下形式即可。

```
\usepackage[backend=biber,style=apa​]{biblatex}​
```

另请仔细检查所有 `\citet` 和 `\citeauthor`引用，需要调整为`\cite`，并进行内容调整。

祝好
LCPU

**Comment by Zorauna** [comment]
感谢～已经解决～
