### ISSUE TITLE
默认加 pdf 属性

### ISSUE THREAD

**Issue by wtyuan96** [CasperVector/pkuthss#93]
发现默认情况下，即便设定了盲审模式（blind）也会添加文档属性信息（包含作者英文名），见：https://github.com/CasperVector/pkuthss/blob/95a75214542124112c38ad4b58a6b442a6c3f30a/tex/pkuthss.cls#L60

是我理解错了吗？盲审模式下给了这些信息不跪了吗？

**Comment by CasperVector** [comment]
之前的确没有意识到这一点，但它好像也没有造成问题。盲审版会用 `\makeblind` 而不是 `\maketitle` 生成封面，前者不会调用 `\setpdfproperties` 所以不会在文档属性中泄露作者信息。我刚在 `pkuthss.cls` 加了一个注释来提示这一点。

**Comment by wtyuan96** [comment]
刚看了下，这个确实应该不会影响。不过overleaf版本的好像把下面这句给换成`\maketitle`了：
https://github.com/CasperVector/pkuthss/blob/86cd17d7ba5a6afb791e5797f8d32666f0b709f8/doc/readme/pkuthss.tex#L78

**Comment by CasperVector** [comment]
哦第三方版本我就管不着了 @@
