### ISSUE TITLE
caspervector引文样式下中文文献引用格式

### ISSUE THREAD

**Issue by sunshineYin** [CasperVector/pkuthss#96]
我在写论文时，遇到需引用中文文献时，格式不太对劲，出现例如“张三, 李四 and 孙五. XXXXX”的引文。但是，“and”这种英文单词不应该出现在中文文献中，这种应该如何设置或修改？

导言区设置为`\usepackage[backend = biber, style = caspervector, utf8, sorting = none]{biblatex}`。

**Comment by sunshineYin** [comment]
大佬可以回复一下吗：）

**Comment by CasperVector** [comment]
请在 `texdoc caspervector` 指向的文档中搜索 `language` 字段的用法。
