### ISSUE TITLE
急求： 参考文献中多了In:字符

### ISSUE THREAD

**Issue by Yujie-Cui** [CasperVector/pkuthss#97]
我在生成参考文献时，参考文献的显示如下：

![image](https://github.com/user-attachments/assets/032515fd-1788-409a-83ed-54ea3acbac15)
但是我在别人论文里面的参考文献中均没有看到In:， 求问怎么去掉呢？ 急求

万分感谢！！！

**Comment by CasperVector** [comment]
`\newbibmacro*{cein:}{}`
